[project]
name = "txt2sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.4.2",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
]
